/* Встроенные данные для демо-режима (когда Supabase ещё не подключён).
   Совпадают с seed-данными в supabase/schema.sql. */
window.DEMO_DATA = {
  recipes: [
    {
      id: 'demo-challah',
      slug: 'challah',
      title: 'Пышная Хала',
      emoji: '🍞',
      description: 'Мягкая, воздушная хала с золотистой корочкой. По этому рецепту пекли наши бабушки — простые ингредиенты, немного терпения и много любви.',
      category: 'Выпечка',
      kosher: 'Пареве',
      occasion: 'Шаббат',
      time_minutes: 180,
      servings: 12,
      yield_text: '2 халы',
      ingredients: [
        { name: 'Мука пшеничная (в/с)', qty: '700 г', key: 'flour' },
        { name: 'Дрожжи сухие', qty: '10 г', key: 'yeast' },
        { name: 'Сахар', qty: '60 г', key: 'sugar' },
        { name: 'Соль', qty: '10 г', key: '' },
        { name: 'Яйца', qty: '3 шт', key: 'eggs' },
        { name: 'Масло растительное', qty: '80 мл', key: 'oil' },
        { name: 'Вода тёплая', qty: '280 мл', key: '' },
        { name: 'Кунжут (для посыпки)', qty: '2 ст.л.', key: 'sesame' },
      ],
      steps: [
        'Опара. Растворите дрожжи и 1 ч.л. сахара в тёплой воде. Оставьте на 10 минут до появления пены.',
        'Тесто. Смешайте муку, соль, сахар. Добавьте опару, 2 яйца и масло. Вымешивайте 10 минут до гладкости.',
        'Подъём. Накройте тесто плёнкой. Оставьте в тёплом месте на 1.5–2 часа — объём должен удвоиться.',
        'Плетение. Разделите тесто на 6 равных частей. Сплетите по 3 жгута в косу. Выложите на противень.',
        'Расстойка. Накройте полотенцем, оставьте ещё на 40 минут. Смажьте взбитым яйцом, посыпьте кунжутом.',
        'Выпечка. Духовка 180°С, 25–30 минут до золотистой корочки. Готово, когда постукивание по дну звучит глухо.',
      ],
      status: 'published',
      featured: true,
      author: 'Кухня общины',
    },
    {
      id: 'demo-latkes',
      slug: 'latkes',
      title: 'Хрустящие латкес',
      emoji: '🥞',
      description: 'Картофельные оладьи на Хануку — хрустящие снаружи, мягкие внутри.',
      category: 'Выпечка',
      kosher: 'Пареве',
      occasion: 'Ханука',
      time_minutes: 45,
      servings: 6,
      yield_text: '18 оладий',
      ingredients: [
        { name: 'Картофель', qty: '1 кг', key: 'other' },
        { name: 'Лук репчатый', qty: '1 шт', key: 'other' },
        { name: 'Яйца', qty: '2 шт', key: 'eggs' },
        { name: 'Мука', qty: '3 ст.л.', key: 'flour' },
        { name: 'Соль, перец', qty: 'по вкусу', key: 'spice' },
        { name: 'Масло растительное', qty: 'для жарки', key: 'oil' },
      ],
      steps: [
        'Натрите картофель и лук на крупной тёрке.',
        'Отожмите лишнюю жидкость через марлю — чем суше масса, тем хрустящее латкес.',
        'Добавьте яйца, муку, соль и перец. Перемешайте.',
        'Жарьте на хорошо разогретом масле по 3–4 минуты с каждой стороны до золотистого цвета.',
        'Выложите на бумажное полотенце, подавайте горячими.',
      ],
      status: 'draft',
      featured: false,
      author: 'Кухня общины',
    },
  ],
  stores: [
    { id: 's1', name: 'Магазин «Мизрахи»',   address: 'ул. Назарбаева, 44',    badge: 'Кошер',       is_kosher: true,  categories: ['flour','yeast','sugar','eggs','oil','sesame','spice','other'], sort_order: 1 },
    { id: 's2', name: 'Green Mall',          address: 'пр. Достык, 111',       badge: 'Супермаркет', is_kosher: false, categories: ['flour','yeast','sugar','oil','other'], sort_order: 2 },
    { id: 's3', name: 'Magnum',              address: 'ул. Байтурсынова, 141', badge: 'Супермаркет', is_kosher: false, categories: ['flour','sugar','oil','other'], sort_order: 3 },
    { id: 's4', name: 'Small',               address: 'пр. Аль-Фараби, 77',    badge: 'Супермаркет', is_kosher: false, categories: ['oil','other'], sort_order: 4 },
    { id: 's5', name: 'Рынок Зелёный базар', address: 'ул. Зенкова, 59',       badge: 'Рынок',       is_kosher: false, categories: ['eggs','sesame','spice','other'], sort_order: 5 },
  ],
  submissions: [
    { id: 'sub1', name: 'Рахель А.', contact: '+7 777 000 00 00', title: 'Чолнт по-бабушкиному', body: 'Мясо, фасоль, перловка, картофель. Ставим в духовку в пятницу вечером на 100°С до субботнего обеда.', status: 'pending', created_at: '2026-06-05T10:00:00Z' },
  ],
};
